version: '3.4'

services:
  teste:
    container_name: teste
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

  poc.gateway:
    container_name: poc.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - teste
    ports:
      - "8010:80"